import type { Metadata } from "next";
import NotesSidebar from "../_components/NotesSidebar";

import CreateNoteButton from "../_ui/CreateNoteButton";
import InfoPanel from "../_components/InfoPanel";
import SidebarNotes from "../_ui/SidebarNotes";
import { Suspense } from "react";
import Loader from "../_ui/Loader";
import EmptyNotes from "../_ui/EmptyNotes";
import { getAllNotes } from "@/app/_libs/services";

export const metadata: Metadata = {
  title: "Dashboard | Notes",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  const AllNotes = await getAllNotes();
  return (
    <div className="grid divide-x divide-neutral-200 lg:h-[calc(100vh-81px)] lg:grid-cols-[290px_1fr_290px]">
      <NotesSidebar>
        <CreateNoteButton />
        {AllNotes && AllNotes.length > 0 ? (
          <Suspense fallback={<Loader />}>
            <SidebarNotes AllNotes={AllNotes} />
          </Suspense>
        ) : (
          <EmptyNotes>
            You don’t have any notes yet. Start a new note to capture your
            thoughts and ideas./n/n No notes match your search. Try a different
            keyword or create a new note.
          </EmptyNotes>
        )}
      </NotesSidebar>
      <WorkspaceArea>{children}</WorkspaceArea>

      <InfoPanel />
    </div>
  );
}
