import type { Metadata } from "next";
import NotesSidebar from "../_components/NotesSidebar";
import EmptyNotes from "../_ui/EmptyNotes";
import CreateNoteButton from "../_ui/CreateNoteButton";
import { getAllNotes } from "../../_libs/services";
import SidebarNotes from "../_ui/SidebarNotes";
import { Suspense } from "react";
import Loader from "../_ui/Loader";
import TagTextNote from "../_ui/TagTextNote";

export const metadata: Metadata = {
  title: "Dashboard | Notes",
  description: "Generated by create next app",
};

export default async function Page({
  children,
}: {
  children: React.ReactNode;
  searchParams: { tag?: string };
}) {
  const AllNotes = await getAllNotes();

  return (
    <div className="grid divide-x divide-neutral-200 lg:h-[calc(100vh-81px)] lg:grid-cols-[290px_1fr_290px]">
      <NotesSidebar AllNotes={AllNotes} />

      <div>{children}</div>
    </div>
  );
}
