import type { Metadata } from "next";
import NotesSidebar from "../_components/NotesSidebar";
import EmptyNotes from "../_ui/EmptyNotes";
import CreateNoteButton from "../_ui/CreateNoteButton";
import InfoPanel from "../_components/InfoPanel";
import { getArchivedNotes, getNoteById } from "@/app/_libs/services";
import SidebarNotes from "../_ui/SidebarNotes";
import { Suspense } from "react";
import Loader from "../_ui/Loader";
import WorkSpaceForm from "../_components/WorkSpaceForm";

export const metadata: Metadata = {
  title: "Archived | Notes",
  description: "Generated by create next app",
};

type PageProps = {
  searchParams: {
    tag?: string;
    mode?: string;
    id?: string;
  };
};

// FIXME:Empty notes text
export default async function Page({ searchParams }: PageProps) {
  let detailedNotes;
  let notes;

  const { tag, mode, id } = await searchParams;
  const ArchivedNotes = await getArchivedNotes();

  if (id && mode === "read") {
    detailedNotes = await getNoteById(id);
  }

  if (tag) {
    notes = ArchivedNotes.filter((note) => note.tags.includes(tag));
  } else {
    notes = ArchivedNotes;
  }

  return (
    <div className="grid divide-x divide-neutral-200 dark:divide-neutral-800 lg:h-[calc(100vh-81px)] lg:grid-cols-[290px_1fr] bg-white dark:bg-[#0E121B]">
      <NotesSidebar>
        <CreateNoteButton />
        {ArchivedNotes && ArchivedNotes.length > 0 ? (
          <Suspense fallback={<Loader />}>
            <SidebarNotes currentId={id} AllNotes={notes} />
          </Suspense>
        ) : (
          <EmptyNotes>
            You don’t have any notes yet. Start a new note to capture your
            thoughts and ideas.
            <br />
            <br />
            No notes match your search. Try a different keyword or create a new
            note.
          </EmptyNotes>
        )}
      </NotesSidebar>
      <div className="h-full overflow-auto scroll-hidden">
        <Suspense fallback={<p>Loading...</p>}>
          {mode || id ? (
            <div className="grid divide-x divide-neutral-200 dark:divide-neutral-800 lg:h-[calc(100vh-81px)] lg:grid-cols-[1fr_290px]">
              <div className="h-full overflow-auto scroll-hidden p-6">
                <WorkSpaceForm key={id} noteToEdit={detailedNotes} />
              </div>
              <InfoPanel noteId={id} />
            </div>
          ) : null}
        </Suspense>
      </div>
    </div>
  );
}
